live_config_reload = true
import = ["/home/mrgeek/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
builtin_box_drawing = false
size = 12

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 1.0

[window.class]
instance = "Alacritty"
general = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0
